
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.scripting.flexcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STOP = 14;
  public static final int NAMES = 15;
  public static final int BUSCAR_ST = 5;
  public static final int PARENC = 24;
  public static final int PARENA = 23;
  public static final int STUDENT = 3;
  public static final int CC = 20;
  public static final int MEN = 22;
  public static final int CA = 19;
  public static final int NUM = 16;
  public static final int DEL = 10;
  public static final int COMA = 17;
  public static final int EOF = 0;
  public static final int SET = 8;
  public static final int STEP = 13;
  public static final int BREAK = 9;
  public static final int MOST_CUR = 7;
  public static final int RUN = 12;
  public static final int PRINT = 11;
  public static final int error = 1;
  public static final int MAY = 21;
  public static final int MOST_ST = 6;
  public static final int PCOMA = 18;
  public static final int EL_ST = 4;
  public static final int CURSO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURSO",
  "STUDENT",
  "EL_ST",
  "BUSCAR_ST",
  "MOST_ST",
  "MOST_CUR",
  "SET",
  "BREAK",
  "DEL",
  "PRINT",
  "RUN",
  "STEP",
  "STOP",
  "NAMES",
  "NUM",
  "COMA",
  "PCOMA",
  "CA",
  "CC",
  "MAY",
  "MEN",
  "PARENA",
  "PARENC"
  };
}

